---
nfs-subdir-external-provisioner:
  enabled: true
  nfs:
    server: 192.168.64.160
    path: /
    reclaimPolicy: Retain
  storageClass:
    defaultClass: false
    name: nfs-client


storage:
  archived:
    mountPath: /persistentvolumes
    cleanup:
      cron: "2 1 * * *"
      days_to_keep: 30
      enabled: true
