{{ if index .Values "molgenis-auth" "enabled" -}}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
{{ include "molgenis-armadillo.labels" . | indent 4 }}
type: Opaque
data:
  CLIENT_ID: {{ $.Values.minio.environment.MINIO_IDENTITY_OPENID_CLIENT_ID | b64enc | quote }}
  CLIENT_SECRET: {{ $.Values.shared.client_secret | b64enc | quote }}
  FUSION_API_TOKEN: {{ index $.Values "molgenis-auth" "secret" "api_token" | b64enc | quote }}
  APP_SESSION_SECRET: {{ uuidv4 | b64enc | quote }}
{{ end -}}