apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdRestore"
metadata:
  # The restore CR name must be the same as spec.etcdCluster.name
  name: vault-etcd
  namespace: vault-operator
spec:
  etcdCluster:
    # The namespace is the same as this EtcdRestore CR
    name: vault-etcd
  backupStorageType: ABS
  abs:
    path: vault/backup
    absSecret: abs