{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-ingress"
  labels:
    app:  {{ $.Values.opencpu.name }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if $.Values.ingress.tls }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end }}
    {{- if $.Values.ingress.firewall.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ template "joinListWithComma" $.Values.ingress.firewall.rules }}
    {{- end }}
    {{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" $.Values.ingress.path }}
          pathType: Prefix
          backend:
            service:
              name: "{{ $.Release.Name }}-{{ $.Values.service.name }}"
              port:
                number: {{ $.Values.service.port }}
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ $.Values.ingress.tls.tlsSecret }}
{{- end }}
---
{{- end }}
{{- end }}