# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

website:
  name: molgenis-website
  strategy:
    type: Recreate
  restartPolicy: Always
  image:
    repository: registry.molgenis.org
    name: molgenis/website
    tag: latest
    pullPolicy: Always
    # only specify when authenticating to dockerhub
    # pullSecret: dockerhub
  service:
    name: molgenis-website
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
  - name: site.dev.molgenis.org
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
