apiVersion: v1
namespace: awx
kind: Secret
metadata:
  name: kube-config
  labels:
    app: {{ template "awx.name" . }}
    chart: {{ template "awx.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  config: |
    {{ .Values.services.kube.config }}