dependencies:
- name: elasticsearch
  version: 7.15.0
  repository: https://helm.elastic.co
- name: kibana
  version: 7.15.0
  repository: https://helm.elastic.co
- name: logstash
  version: 7.15.0
  repository: https://helm.elastic.co
