{{ if not .Values.secret.nameOverride -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "molgenis-auth.secretname" . }}
  labels:
{{ include "molgenis-auth.labels" . | indent 4 }}
type: Opaque
data:
  CLIENT_ID: {{ $.Values.secret.client_id | b64enc | quote }}
  CLIENT_SECRET: {{ $.Values.secret.client_secret | b64enc | quote }}
  FUSION_API_TOKEN: {{ $.Values.secret.api_token | b64enc | quote }}
  APP_SESSION_SECRET: {{ uuidv4 | b64enc | quote }}
{{- end }}