pipeline {
  agent {
    kubernetes {
      label 'shared'
    }
  }
  stages {
    stage("Cleanup") {
      steps {
        container('vault') {
          sh "mkdir ${JENKINS_AGENT_WORKDIR}/.rancher"
          sh(script: 'vault read -field=value secret/ops/jenkins/rancher/cli2.json > ${JENKINS_AGENT_WORKDIR}/.rancher/cli2.json')
        }
        container('rancher') {
          sh "rancher app | awk '{print \$2}' | grep preview- > preview.list"
          sh "xargs rancher app delete < preview.list"
        }
      }
    }
  }
}
