apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "variant-formatter.fullname" . }}
  labels:
{{ include "variant-formatter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "variant-formatter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "variant-formatter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: seqrepo
          image: "{{ .Values.seqrepo.image.repository }}:{{ .Values.seqrepo.image.tag }}"
          imagePullPolicy: {{ .Values.seqrepo.image.pullPolicy }}
          env:
            - name: SEQREPO_DATA_RELEASE
              value: {{ .Values.seqrepo.dataRelease }}
          volumeMounts:
            - mountPath: /usr/local/share/seqrepo
              name: seqrepo
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/local/share/seqrepo
              name: seqrepo
          env:
            - name: MAX_WORKERS
              value: {{ .Values.maxWorkers | quote }}
            - name: HGVS_SEQREPO_DIR
              value: /usr/local/share/seqrepo/{{ .Values.seqrepo.dataRelease }}
            - name: UTA_DB_URL
              value: postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.postgresqlDatabase }}/{{ .Values.uta.version }}
          ports:
            - name: http
              containerPort: 1234
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: seqrepo
        {{- if .Values.seqrepo.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.seqrepo.persistence.existingClaim | default (include "variant-formatter.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
