pipeline {
    agent {
        kubernetes {
            label 'shared'
        }
    }
    environment {
        CHART_VERSION = '1.3.1'
    }
    stages {
        stage("Deploy") {
            when {
                equals expected: 'install', actual: params.ACTION
            }
            steps {
                container('vault') {
                    sh "mkdir /home/jenkins/.rancher"
                    sh(script: 'vault read -field=value secret/ops/jenkins/rancher/cli2.json > /home/jenkins/.rancher/cli2.json')
                }
                container('rancher') {
                    sh "rancher context switch dev-molgenis"
                    sh "rancher apps install " +
                            "-n preview-${TAG.toLowerCase()} " +
                            "molgenis-helm-molgenis " +
                            "preview-${TAG.toLowerCase()} " +
                            "--version ${CHART_VERSION} " +
                            "--no-prompt " +
                            "--set adminPassword=admin " +
                            "--set environment=dev " +
                            "--set image.tag=${TAG} " +
                            "--set image.repository=${LOCAL_REGISTRY} " +
                            "--set image.pullPolicy=Always"
                }
                hubotSend message: "Deployed https://preview-${TAG}.dev.molgenis.org"
            }
        }
        stage("Delete") {
            when {
                equals expected: 'delete', actual: params.ACTION
            }
            steps {
                container('vault') {
                    sh "mkdir /home/jenkins/.rancher"
                    sh(script: 'vault read -field=value secret/ops/jenkins/rancher/cli2.json > /home/jenkins/.rancher/cli2.json')
                }
                container('rancher') {
                    sh "rancher context switch dev-molgenis"
                    sh "rancher apps delete preview-${TAG.toLowerCase()}"
                }
                hubotSend message: "Deleted preview-${TAG.toLowerCase()}"
            }
        }
        stage("List") {
            when {
                equals expected: 'list', actual: params.ACTION
            }
            steps {
                container('vault') {
                    sh "mkdir /home/jenkins/.rancher"
                    sh(script: 'vault read -field=value secret/ops/jenkins/rancher/cli2.json > /home/jenkins/.rancher/cli2.json')
                }
                container('rancher') {
                    sh "rancher context switch dev-molgenis"
                    script {
                        env.LIST = sh script:"rancher apps ls", returnStdout: true
                    }
                }
                hubotSend message: "Dit draait er allemaal:\n```${LIST}```"
            }
        }
    }
}
