{
 "title": "Total UP websites",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total UP website",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(probe_http_status_code==200)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(probe_http_status_code!=200)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "Websites UP",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "probe_http_status_code==200" }
   ]
  },
  {
   "title": "Websites DOWN",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "probe_http_status_code!=200" }
   ]
  }
 ]
}