replicaCount: 1

user: drugis
password: xxxxx

image:
  repository: bitnami/matomo
  pullPolicy: IfNotPresent
  tag: "4.5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: analytics.drugis.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

mariadb: 
  db:
    user: drugis
    password: xxxxx
    name: drugis

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}