apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "matomo.fullname" . }}
  labels:
    app: {{ template "matomo.name" . }}
    chart: {{ template "matomo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  matomo-password: {{ .Values.password | b64enc | quote }}